// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDPphEEv6TZlkZlx_fSH6vFB77T0KxIJM',
    appId: '1:21048175894:web:b308cb0cb23e8bce51f437',
    messagingSenderId: '21048175894',
    projectId: 'fir-auth-demo-689c7',
    authDomain: 'fir-auth-demo-689c7.firebaseapp.com',
    storageBucket: 'fir-auth-demo-689c7.appspot.com',
    measurementId: 'G-CTQPTYKL91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCohffG-cTTL6J3XeEQPxgZl797ECQDAow',
    appId: '1:21048175894:android:075fb001e49e19b451f437',
    messagingSenderId: '21048175894',
    projectId: 'fir-auth-demo-689c7',
    storageBucket: 'fir-auth-demo-689c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXT7I-NXtr4fj_IlSVXLUB3YuuRF4Hti0',
    appId: '1:21048175894:ios:80baecdc0ad7ddcf51f437',
    messagingSenderId: '21048175894',
    projectId: 'fir-auth-demo-689c7',
    storageBucket: 'fir-auth-demo-689c7.appspot.com',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXT7I-NXtr4fj_IlSVXLUB3YuuRF4Hti0',
    appId: '1:21048175894:ios:80baecdc0ad7ddcf51f437',
    messagingSenderId: '21048175894',
    projectId: 'fir-auth-demo-689c7',
    storageBucket: 'fir-auth-demo-689c7.appspot.com',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDPphEEv6TZlkZlx_fSH6vFB77T0KxIJM',
    appId: '1:21048175894:web:4ce488cfb639c6a951f437',
    messagingSenderId: '21048175894',
    projectId: 'fir-auth-demo-689c7',
    authDomain: 'fir-auth-demo-689c7.firebaseapp.com',
    storageBucket: 'fir-auth-demo-689c7.appspot.com',
    measurementId: 'G-1HCFEQD7SG',
  );
}
